Catalog page and Chat-specific catalog
andrzejczukm/ChatRoom pull request #40
Opened 2024-05-25 16:22 UTC by bieleckipiotr

proszę o review :))

2024-05-27 08:42 UTC, maciejors requested changes
Looks good, mega job. I left a few suggestions regarding the styling

2024-05-27 08:42 UTC, maciejors commented on src/routes/catalog/+page.svelte
> +            <a href="catalog/{imageObj.chatId}" target="_blank">
I think we should remove target="_blank" from there

2024-05-27 08:42 UTC, maciejors commented on src/routes/catalog/[chatId]/+page.svelte
> +<button on:click={downloadSelected} id='downloadSelected'> Download Selected</button>
This button could use some styling. I would maybe center it, and also add classes "btn btn-primary" which are defined in app.css and will make this button look like all other buttons in the app

2024-05-27 08:42 UTC, maciejors commented on src/routes/catalog/[chatId]/+page.svelte
> +    border-color: blue;
Maybe we could change this colour to our main colour instead of blue so that there is not too many different colours

2024-05-27 08:42 UTC, maciejors commented on src/routes/catalog/+page.svelte
> +    background-color: #709692;
I'm not sure if I like changing background color here, but it's up to you

2024-05-27 08:42 UTC, maciejors commented on src/routes/catalog/+page.svelte
> +            <a href="catalog/{imageObj.chatId}" target="_blank">
here also target blank

2024-05-27 08:42 UTC, maciejors commented on src/routes/catalog/+page.svelte
> +            <figcaption>{imageObj.chatName}</figcaption></a>
maybe you could style this so that the text is not blue but has color: whitesmoke (or the main colour if we decide to remove the backgroud colour)

2024-05-27 22:07 UTC, bieleckipiotr commented
prettify

2024-05-28 08:21 UTC, maciejors approved these changes
great work

2024-05-28 08:22 UTC, merged